/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IotRouteImport } from './routes/iot'
import { Route as LogbookRouteImport } from './routes/logbook'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as DocIdRouteImport } from './routes/doc.$id'
import { Route as HandoffIdRouteImport } from './routes/handoff.$id'
import { Route as JournalIdRouteImport } from './routes/journal.$id'
import { Route as JournalNewRouteImport } from './routes/journal.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IotRoute = IotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => rootRouteImport,
} as any)
const LogbookRoute = LogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffIdRoute = HandoffIdRouteImport.update({
  id: '/handoff/$id',
  path: '/handoff/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIdRoute = JournalIdRouteImport.update({
  id: '/journal/$id',
  path: '/journal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalNewRoute = JournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/iot': typeof IotRoute
  '/logbook': typeof LogbookRoute
  '/login': typeof LoginRoute
  '/warehouse': typeof WarehouseRoute
  '/doc/$id': typeof DocIdRoute
  '/handoff/$id': typeof HandoffIdRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/new': typeof JournalNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/iot': typeof IotRoute
  '/logbook': typeof LogbookRoute
  '/login': typeof LoginRoute
  '/warehouse': typeof WarehouseRoute
  '/doc/$id': typeof DocIdRoute
  '/handoff/$id': typeof HandoffIdRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/new': typeof JournalNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/iot': typeof IotRoute
  '/logbook': typeof LogbookRoute
  '/login': typeof LoginRoute
  '/warehouse': typeof WarehouseRoute
  '/doc/$id': typeof DocIdRoute
  '/handoff/$id': typeof HandoffIdRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/new': typeof JournalNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/iot'
    | '/logbook'
    | '/login'
    | '/warehouse'
    | '/doc/$id'
    | '/handoff/$id'
    | '/journal/$id'
    | '/journal/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/iot'
    | '/logbook'
    | '/login'
    | '/warehouse'
    | '/doc/$id'
    | '/handoff/$id'
    | '/journal/$id'
    | '/journal/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/iot'
    | '/logbook'
    | '/login'
    | '/warehouse'
    | '/doc/$id'
    | '/handoff/$id'
    | '/journal/$id'
    | '/journal/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  IotRoute: typeof IotRoute
  LogbookRoute: typeof LogbookRoute
  LoginRoute: typeof LoginRoute
  WarehouseRoute: typeof WarehouseRoute
  DocIdRoute: typeof DocIdRoute
  HandoffIdRoute: typeof HandoffIdRoute
  JournalIdRoute: typeof JournalIdRoute
  JournalNewRoute: typeof JournalNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iot': {
      id: '/iot'
      path: '/iot'
      fullPath: '/iot'
      preLoaderRoute: typeof IotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logbook': {
      id: '/logbook'
      path: '/logbook'
      fullPath: '/logbook'
      preLoaderRoute: typeof LogbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id': {
      id: '/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$id': {
      id: '/handoff/$id'
      path: '/handoff/$id'
      fullPath: '/handoff/$id'
      preLoaderRoute: typeof HandoffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$id': {
      id: '/journal/$id'
      path: '/journal/$id'
      fullPath: '/journal/$id'
      preLoaderRoute: typeof JournalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/new': {
      id: '/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof JournalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  IotRoute: IotRoute,
  LogbookRoute: LogbookRoute,
  LoginRoute: LoginRoute,
  WarehouseRoute: WarehouseRoute,
  DocIdRoute: DocIdRoute,
  HandoffIdRoute: HandoffIdRoute,
  JournalIdRoute: JournalIdRoute,
  JournalNewRoute: JournalNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
